# -*- coding: utf-8 -*-
"""BioTactix AI Master Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_x1CvjamBG6FaKCRzCeOQBamzk7CrVY
"""

import time

# =====================================================================
# BIOTACTIX AI: SOVEREIGN ROSTER, PRESSURE VFS, & MEDICAL ALARMS
# =====================================================================

# 1. THE 40-SLOT ROSTER (Now tracking hardware sensors and physical impact)
roster_registry = {
    f"Slot_{i:02d}": {
        "status": "E", "jersey": None, "fatigue": 0, "reaction_ms": 0, "sensor_status": "OK", "impact_g": 0
    } for i in range(1, 41)
}

# 2. INITIALIZE STARTING NODES
roster_registry["Slot_01"] = {"status": "A", "jersey": "A_10", "fatigue": 92, "reaction_ms": 350, "sensor_status": "OK", "impact_g": 2}
roster_registry["Slot_02"] = {"status": "A", "jersey": "A_09", "fatigue": 40, "reaction_ms": 150, "sensor_status": "OFFLINE", "impact_g": 0}
roster_registry["Slot_23"] = {"status": "A", "jersey": "B_07", "fatigue": 88, "reaction_ms": 400, "sensor_status": "OK", "impact_g": 14}
roster_registry["Slot_14"] = {"status": "A", "jersey": "B_11", "fatigue": 20, "reaction_ms": 110, "sensor_status": "OK", "impact_g": 1}

def build_active_kernel():
    """Atomic Swap: Creates a temporary 2D array of ONLY 'Active' players."""
    return [data for slot, data in roster_registry.items() if data["status"] == "A"]

def calculate_pressure_index(clock, score_diff):
    if clock >= 80 and score_diff <= 1:
        return "CRITICAL_PRESSURE"
    elif clock == 45:
        return "INTERVAL_REVIEW"
    return "MODERATE_PRESSURE"

# =====================================================================
# THE 4-TIER OUTPUT GENERATORS (IBM GRANITE SIMULATIONS)
# =====================================================================

def generate_halftime_strategy_report(kernel):
    print("\n=== 📊 IBM GRANITE: INTERVAL STRATEGY REPORT (COACH'S TABLET) ===")
    for player in kernel:
        if player['sensor_status'] == "OK":
            battery = 100 - player['fatigue']
            if battery < 20:
                print(f"⚠️ STRATEGY ALERT: Player {player['jersey']} biological battery at {battery}%. High risk of spatial mesh fracture in 2nd Half. Recommend substitution by 60th minute.")

def generate_live_commentator_feed(kernel, pressure):
    print("\n=== 🎙️ IBM GRANITE: LIVE COMMENTATOR FEED (MINUTE-BY-MINUTE) ===")
    for player in kernel:
        if player['fatigue'] > 85:
            print(f"📺 PROMPT: 'Fans, Player {player['jersey']} is experiencing severe lactic deficit. Combined with {pressure}, their {player['reaction_ms']}ms reaction delay is a biological inevitability, not a lack of effort.'")

def generate_live_coach_dashboard(kernel, pressure):
    print("\n=== 🧠 IBM GRANITE: LIVE TACTICAL ANOMALY DASHBOARD (COACH'S TABLET) ===")
    for player in kernel:
        if player['reaction_ms'] > 300:
            print(f"🚨 TACTICAL ANOMALY: Player {player['jersey']} reaction to ball trajectory delayed by {player['reaction_ms']}ms. \n   -> JUSTIFICATION: GPS confirms sustained lactic buildup. Pressure context ({pressure}) accelerating cognitive fog. \n   -> ACTION: Defensive mesh is vulnerable. Warm up substitutes.")

def check_medical_and_hardware_alarms(kernel):
    print("\n=== 🚑 BIOTACTIX SAFETY OVERRIDE (REFEREE & MEDICAL TABLETS) ===")
    for player in kernel:
        if player['sensor_status'] == "OFFLINE":
            print(f"[HARDWARE ALARM] Player {player['jersey']}: Sensor Vest offline. Data stream lost. Equipment change required at next stoppage.")
        if player['impact_g'] > 10:
            print(f"[MEDICAL EMERGENCY] Player {player['jersey']}: {player['impact_g']}G physical impact detected. Immediate concussion protocol required. Halting play.")

def generate_post_match_analyst_report(kernel):
    print("\n=== 📈 IBM GRANITE: POST-MATCH ANALYST SUMMARY (FULL-TIME) ===")
    print("MATCH POST-MORTEM: The momentum shift in the final 10 minutes was driven entirely by Cognitive Sync-Drop.")
    for player in kernel:
        if player['fatigue'] > 80:
            print(f"-> Player {player['jersey']} finished with an {player['fatigue']}% fatigue index, directly correlating with a 30% breakdown in their defensive spatial geometry.")

# =====================================================================
# SIMULATION EXECUTION: MATCH TIMELINE
# =====================================================================
print("/// BIOTACTIX AI: MATCH INGESTION ONLINE ///")

active_kernel = build_active_kernel()

# --- PHASE 1: HALF-TIME ---
print("\n" + "="*50)
print("[MATCH CLOCK: 45:00] | SCORE: 0-0 | PHASE: HALF-TIME")
print("="*50)
generate_halftime_strategy_report(active_kernel)
time.sleep(1)

# --- PHASE 2: LIVE CRITICAL PLAY ---
print("\n" + "="*50)
print("[MATCH CLOCK: 82:00] | SCORE: 1-0 | PHASE: LIVE PLAY (HIGH TENSION)")
print("="*50)
current_pressure = calculate_pressure_index(clock=82, score_diff=1)
generate_live_commentator_feed(active_kernel, current_pressure)
generate_live_coach_dashboard(active_kernel, current_pressure)
time.sleep(1)

# --- PHASE 3: EMERGENCY EVENT ---
print("\n" + "="*50)
print("[MATCH CLOCK: 85:00] | SCORE: 1-0 | PHASE: EMERGENCY STOPPAGE")
print("="*50)
check_medical_and_hardware_alarms(active_kernel)
time.sleep(1)

# --- PHASE 4: FULL-TIME ---
print("\n" + "="*50)
print("[MATCH CLOCK: 90:00] | SCORE: 1-0 | PHASE: FULL-TIME")
print("="*50)
generate_post_match_analyst_report(active_kernel)